-- 코드를 입력하세요
SELECT T.CAR_ID, T.AVERAGE_DURATION
FROM (SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) AS T
WHERE T.AVERAGE_DURATION >= 7
ORDER BY T.AVERAGE_DURATION DESC , T.CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;