-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH ,COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
,ROUND((COUNT(DISTINCT UI.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021) *  1.0),1) AS PUCHASED_RATIO
FROM USER_INFO AS UI
INNER JOIN (SELECT SALES_DATE, USER_ID FROM ONLINE_SALE)
AS OS ON UI.USER_ID = OS.USER_ID 
WHERE YEAR(UI.JOINED) = 2021 AND OS.SALES_DATE IS NOT NULL
GROUP BY 1,2 
ORDER BY YEAR, MONTH;





#전체 수를 어떻게 구하지?
#년과 달만 합쳐진 것으로 묶는다고 생각하면 된다.
#나중에 group by user_id로 개수를 세는 것이다.