-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF AS F
JOIN (SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDERS, FLAVOR FROM JULY GROUP BY FLAVOR) AS J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + TOTAL_ORDERS) DESC
LIMIT 3;